import type { Hotspot, Material } from './types';

export const MATERIALS: Material[] = [
  'Agate',
  'Jasper',
  'Jade',
  'Petrified wood',
  'Quartz',
  'Fossil caution',
  'Gold indicators',
  'Unusual minerals',
];

export const HOTSPOTS: Hotspot[] = [
  {
    id: 'south-pass-granite-belt',
    name: 'South Pass Granite Belt',
    county: 'Fremont / Sweetwater',
    lat: 42.43,
    lng: -108.78,
    targetMaterials: ['Jade', 'Quartz', 'Gold indicators', 'Unusual minerals'],
    geologyUnit: 'Archean greenstone and granitic terrain',
    landManager: 'Mixed BLM / state / private parcels',
    accessStatus: 'Verify access',
    claimRisk: 'High',
    roadProximity: 'County-road approach with claim checks required',
    terrain: 'Open high desert with exposed bedrock and seasonal road issues',
    evidence: [
      'Historic South Pass mineral district creates strong mineral-system signal.',
      'Greenstone/granite contacts are useful prospecting context for harder rock targets.',
      'Good first candidate for validating the claim-risk workflow.',
    ],
    cautions: [
      'Mining claim density can be high. Do not collect on active claims without permission.',
      'Private inholdings and seasonal access can break routes.',
    ],
    sourceNotes: ['Use WSGS geology, USGS mineral occurrence records, BLM MLRS claims, and county roads.'],
    scoreFactors: {
      geology: 5,
      mineralEvidence: 5,
      access: 3,
      roadProximity: 4,
      personalHistory: 2,
      claimPenalty: 3,
      terrainPenalty: 2,
    },
  },
  {
    id: 'wamsutter-agate-flats',
    name: 'Wamsutter Agate Flats',
    county: 'Sweetwater',
    lat: 41.68,
    lng: -107.95,
    targetMaterials: ['Agate', 'Jasper', 'Unusual minerals'],
    geologyUnit: 'Eocene basin margin sediments and volcanic ash influence',
    landManager: 'BLM-dominant checkerboard context',
    accessStatus: 'Likely public',
    claimRisk: 'Medium',
    roadProximity: 'Close to I-80 corridor and gravel two-track systems',
    terrain: 'Windy basin flats with mud and clay risk after storms',
    evidence: [
      'Basin-margin lag gravels and silica-rich float are a practical agate/jasper search pattern.',
      'Large public-land blocks make this efficient for first-pass field validation.',
      'Good MVP zone because approach roads and access questions are visible.',
    ],
    cautions: [
      'Checkerboard ownership requires parcel-level verification before collecting.',
      'Oil and gas roads can look public but may have restrictions.',
    ],
    sourceNotes: ['Use BLM surface management, road layers, and WSGS surficial geology.'],
    scoreFactors: {
      geology: 4,
      mineralEvidence: 3,
      access: 5,
      roadProximity: 5,
      personalHistory: 2,
      claimPenalty: 1,
      terrainPenalty: 1,
    },
  },
  {
    id: 'eden-valley-petrified-wood',
    name: 'Eden Valley Petrified Wood Zone',
    county: 'Sweetwater',
    lat: 42.04,
    lng: -109.05,
    targetMaterials: ['Petrified wood', 'Agate', 'Jasper'],
    geologyUnit: 'Eocene fluvial and lake-bed deposits',
    landManager: 'BLM / private mosaic',
    accessStatus: 'Verify access',
    claimRisk: 'Medium',
    roadProximity: 'Moderate; route quality changes quickly after rain',
    terrain: 'Rolling badland benches and dry washes',
    evidence: [
      'Petrified wood potential aligns with basin sedimentary units and historic collecting interest.',
      'Benches and drainages create repeatable search targets.',
      'Useful zone for testing daily weight-limit guidance in the app.',
    ],
    cautions: [
      'Petrified wood has personal-use collection limits.',
      'Avoid vertebrate fossils and cultural materials entirely.',
      'Parcel verification matters before field collection.',
    ],
    sourceNotes: ['Use BLM rock collection guidance, WSGS geology, and surface ownership layers.'],
    scoreFactors: {
      geology: 5,
      mineralEvidence: 4,
      access: 3,
      roadProximity: 3,
      personalHistory: 2,
      claimPenalty: 1,
      terrainPenalty: 2,
    },
  },
  {
    id: 'granite-mountains-wash',
    name: 'Granite Mountains Washes',
    county: 'Natrona / Fremont',
    lat: 42.76,
    lng: -107.52,
    targetMaterials: ['Agate', 'Jasper', 'Quartz', 'Unusual minerals'],
    geologyUnit: 'Precambrian crystalline core with basin-edge gravels',
    landManager: 'Mixed BLM / state / private',
    accessStatus: 'Verify access',
    claimRisk: 'Unknown',
    roadProximity: 'Long gravel approach; plan fuel and weather checks',
    terrain: 'Remote washes, exposed ridges, and limited services',
    evidence: [
      'Crystalline highlands feeding basin gravels create useful float-prospecting context.',
      'Remote footprint may reduce casual collection pressure.',
      'Good candidate for route-planning and offline notes.',
    ],
    cautions: [
      'Remote access creates safety and recovery risk.',
      'Ownership transitions can be hard to see on the ground.',
    ],
    sourceNotes: ['Use WSGS geology, BLM land status, and road/travel layers.'],
    scoreFactors: {
      geology: 4,
      mineralEvidence: 3,
      access: 3,
      roadProximity: 2,
      personalHistory: 1,
      claimPenalty: 1,
      terrainPenalty: 3,
    },
  },
  {
    id: 'semnoe-jasper-rim',
    name: 'Seminoe Jasper Rim',
    county: 'Carbon',
    lat: 42.16,
    lng: -106.88,
    targetMaterials: ['Jasper', 'Agate', 'Quartz'],
    geologyUnit: 'Mixed sedimentary, volcanic, and uplift-margin units',
    landManager: 'BLM / state / recreation-area boundaries nearby',
    accessStatus: 'Verify access',
    claimRisk: 'Medium',
    roadProximity: 'Good approach with recreation restrictions to verify',
    terrain: 'Reservoir rim, washes, and broken slopes',
    evidence: [
      'Uplift margins and drainage reworking are useful for silica-rich float searches.',
      'Road approach is efficient for short validation trips.',
      'Boundary checks make it a useful access-workflow example.',
    ],
    cautions: [
      'Recreation-area and managed-site restrictions may apply.',
      'Water-level and slope conditions can change field safety.',
    ],
    sourceNotes: ['Use land manager boundaries, roads, claims, and WSGS geology.'],
    scoreFactors: {
      geology: 4,
      mineralEvidence: 3,
      access: 3,
      roadProximity: 4,
      personalHistory: 1,
      claimPenalty: 1,
      terrainPenalty: 2,
    },
  },
  {
    id: 'hartville-quartzite-ridge',
    name: 'Hartville Quartzite Ridge',
    county: 'Platte / Goshen',
    lat: 42.44,
    lng: -104.79,
    targetMaterials: ['Quartz', 'Jasper', 'Unusual minerals'],
    geologyUnit: 'Paleozoic and Precambrian uplift exposure',
    landManager: 'Mixed federal / state / private',
    accessStatus: 'Private risk',
    claimRisk: 'Medium',
    roadProximity: 'Sparse legal access; verify before routing',
    terrain: 'Ridges, draws, and ranchland edges',
    evidence: [
      'Older exposed units create interesting mineral and quartzite context.',
      'Useful for testing the app’s private-risk suppression logic.',
      'Potentially interesting, but access quality is the controlling factor.',
    ],
    cautions: [
      'Private land risk is material. Do not assume road access equals collecting permission.',
      'Respect gates, ranch operations, and posted boundaries.',
    ],
    sourceNotes: ['Use surface ownership, county roads, and WSGS bedrock geology.'],
    scoreFactors: {
      geology: 4,
      mineralEvidence: 3,
      access: 1,
      roadProximity: 2,
      personalHistory: 0,
      claimPenalty: 1,
      terrainPenalty: 2,
    },
  },
  {
    id: 'green-river-fossil-caution',
    name: 'Green River Formation Caution Zone',
    county: 'Lincoln / Sweetwater / Uinta',
    lat: 41.86,
    lng: -110.28,
    targetMaterials: ['Fossil caution', 'Petrified wood', 'Unusual minerals'],
    geologyUnit: 'Green River Formation lake beds',
    landManager: 'Mixed BLM / private / state',
    accessStatus: 'Restricted / no-go',
    claimRisk: 'Unknown',
    roadProximity: 'Accessible corridors, but collecting rules drive decision',
    terrain: 'Badlands, lake-bed exposures, and fragile slopes',
    evidence: [
      'High educational geology value and strong map context.',
      'Important to show Gwen where curiosity must be separated from collection.',
      'Useful as a no-go example in the decision engine.',
    ],
    cautions: [
      'Vertebrate fossils are not personal-use collecting targets.',
      'Many fossil localities are private, permitted, or otherwise restricted.',
      'Use for learning and route awareness, not collecting without explicit authorization.',
    ],
    sourceNotes: ['Use BLM fossil guidance, WSGS geology, and parcel/access verification.'],
    scoreFactors: {
      geology: 5,
      mineralEvidence: 5,
      access: 0,
      roadProximity: 4,
      personalHistory: 0,
      claimPenalty: 2,
      terrainPenalty: 2,
    },
  },
  {
    id: 'powder-river-silica-benches',
    name: 'Powder River Silica Benches',
    county: 'Johnson / Campbell',
    lat: 44.06,
    lng: -106.19,
    targetMaterials: ['Agate', 'Jasper', 'Petrified wood'],
    geologyUnit: 'Tertiary basin sediments and terrace gravels',
    landManager: 'BLM / state / private mosaic',
    accessStatus: 'Verify access',
    claimRisk: 'Low',
    roadProximity: 'Moderate access via county roads and two-tracks',
    terrain: 'Benches, draws, and grassland exposure windows',
    evidence: [
      'Terrace and wash lag can concentrate durable silica materials.',
      'Low claim signal makes ownership and road access the main research problem.',
      'Good northern Wyoming validation candidate.',
    ],
    cautions: [
      'Large ranch blocks require careful permission checks.',
      'Some roads become impassable in wet conditions.',
    ],
    sourceNotes: ['Use BLM surface management, WSGS surficial geology, and county access layers.'],
    scoreFactors: {
      geology: 3,
      mineralEvidence: 2,
      access: 3,
      roadProximity: 3,
      personalHistory: 0,
      claimPenalty: 0,
      terrainPenalty: 1,
    },
  },
  {
    id: 'bighorn-foothill-quartz',
    name: 'Bighorn Foothill Quartz Windows',
    county: 'Washakie / Big Horn',
    lat: 44.32,
    lng: -107.87,
    targetMaterials: ['Quartz', 'Jasper', 'Unusual minerals'],
    geologyUnit: 'Uplift-margin sedimentary and crystalline exposure context',
    landManager: 'Forest / BLM / private transitions',
    accessStatus: 'Verify access',
    claimRisk: 'Low',
    roadProximity: 'Forest and county-road approach with seasonal gates',
    terrain: 'Foothill draws, scree, and higher-elevation weather exposure',
    evidence: [
      'Uplift margin provides diverse rock context within compact scouting radius.',
      'Useful for testing seasonal access and land-manager labels.',
      'Better as a research trip than a high-confidence first target.',
    ],
    cautions: [
      'Forest, wilderness, and special-management rules vary by area.',
      'Weather and road closures can invalidate routes.',
    ],
    sourceNotes: ['Use Forest Service/BLM boundaries, WSGS bedrock geology, and seasonal roads.'],
    scoreFactors: {
      geology: 3,
      mineralEvidence: 2,
      access: 3,
      roadProximity: 3,
      personalHistory: 0,
      claimPenalty: 0,
      terrainPenalty: 3,
    },
  },
  {
    id: 'shirley-basin-research-line',
    name: 'Shirley Basin Research Line',
    county: 'Carbon / Natrona',
    lat: 42.35,
    lng: -106.05,
    targetMaterials: ['Agate', 'Jasper', 'Unusual minerals'],
    geologyUnit: 'Basin sediments, volcanic ash influence, and mineral districts nearby',
    landManager: 'BLM / state / private mosaic',
    accessStatus: 'Likely public',
    claimRisk: 'Medium',
    roadProximity: 'Good road geometry with parcel checks',
    terrain: 'Open basin, benches, and wind-exposed flats',
    evidence: [
      'Basin-edge materials and accessible public-land blocks make this efficient to scout.',
      'Good zone for testing side-by-side score comparison against Seminoe.',
      'Potential for repeatable short trips and notes refinement.',
    ],
    cautions: [
      'Energy and mining activity may create restricted access pockets.',
      'Wind and exposure can complicate field days.',
    ],
    sourceNotes: ['Use BLM surface management, MLRS claims, WSGS geology, and roads.'],
    scoreFactors: {
      geology: 4,
      mineralEvidence: 3,
      access: 4,
      roadProximity: 4,
      personalHistory: 1,
      claimPenalty: 1,
      terrainPenalty: 1,
    },
  },
];

export const DATA_SOURCES = [
  {
    name: 'Wyoming State Geological Survey GIS',
    use: 'Bedrock, surficial geology, mineral resource context, and downloadable GIS layers.',
    url: 'https://main.wsgs.wyo.gov/gis',
  },
  {
    name: 'USGS Mineral Resources Data',
    use: 'Mineral occurrence records, mine features, geochemistry, and broader mineral-system evidence.',
    url: 'https://www.usgs.gov/programs/mineral-resources-program/mineral-resources-data',
  },
  {
    name: 'BLM Surface Management Agency',
    use: 'Federal surface-management signal for public/private/agency access triage.',
    url: 'https://gis.blm.gov/wyarcgis/rest/services/Lands/BLM_WY_Surface_Management_Agency/MapServer',
  },
  {
    name: 'BLM MLRS Mining Claims',
    use: 'Active/not-closed mining claim warning layer. Field collection requires claim verification.',
    url: 'https://gis.blm.gov/nlsdb/rest/services/HUB/BLM_Natl_MLRS_Mining_Claims_Not_Closed/MapServer',
  },
  {
    name: 'BLM Wyoming Rockhounding Guide',
    use: 'Personal-use collecting rules, petrified wood limits, fossil cautions, and local office checks.',
    url: 'https://www.blm.gov/documents/wyoming/public-room/brochure/wyoming-rockhounding-guide',
  },
];
